### ISSUE TITLE
Support reading variables from .env file

### ISSUE THREAD

**Issue by AGraber** [Southclaws/pawn-env#2]
While developing it's a hassle to pass everytime the env vars, and it's a common practice to declare them on an `.env` file to make development easier.

**Comment by Southclaws** [comment]
I've had this requested before but I feel it's out of scope for this plugin. Reading from a file isn't related to actual environment variables - it's just a useful devtool. There are also shell helpers for [bash](https://direnv.net/) and [powershell](https://github.com/takekazuomi/posh-direnv) for this too.

After [sampctl dev is merged to master](https://github.com/Southclaws/sampctl/network) this will be possible via sampctl.
